# Generated by Django 3.0.8 on 2020-07-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='arrival_station',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='schedule',
            name='arrival_time',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='schedule',
            name='departure_station',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='schedule',
            name='departure_time',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='schedule',
            name='duration',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='schedule',
            name='train',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
